server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
