spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/live_ecommerce
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8082
