server:
  port: 8084
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/live_commerce
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
management:
  endpoints:
    web:
      exposure:
        include: health,info
